import Foundation

struct CurrencyData {
    static let fiatCurrencies: [Currency] = [
        // TIER 1: Major global currencies (most traded by volume 2024-2025)
        Currency(code: "USD", name: "currency_us_dollar".localized, type: .fiat),
        Currency(code: "EUR", name: "currency_euro".localized, type: .fiat),
        Currency(code: "JPY", name: "currency_japanese_yen".localized, type: .fiat),
        Currency(code: "GBP", name: "currency_british_pound".localized, type: .fiat),
        Currency(code: "CNY", name: "currency_chinese_yuan".localized, type: .fiat),
        Currency(code: "AUD", name: "currency_australian_dollar".localized, type: .fiat),
        Currency(code: "CAD", name: "currency_canadian_dollar".localized, type: .fiat),
        Currency(code: "CHF", name: "currency_swiss_franc".localized, type: .fiat),
        Currency(code: "HKD", name: "currency_hong_kong_dollar".localized, type: .fiat),
        Currency(code: "SGD", name: "currency_singapore_dollar".localized, type: .fiat),
        
        // TIER 2: Regional powerhouses & popular trading pairs
        Currency(code: "NZD", name: "currency_new_zealand_dollar".localized, type: .fiat),
        Currency(code: "SEK", name: "currency_swedish_krona".localized, type: .fiat),
        Currency(code: "NOK", name: "currency_norwegian_krone".localized, type: .fiat),
        Currency(code: "DKK", name: "currency_danish_krone".localized, type: .fiat),
        Currency(code: "KRW", name: "currency_south_korean_won".localized, type: .fiat),
        Currency(code: "INR", name: "currency_indian_rupee".localized, type: .fiat),
        Currency(code: "BRL", name: "currency_brazilian_real".localized, type: .fiat),
        Currency(code: "MXN", name: "currency_mexican_peso".localized, type: .fiat),
        Currency(code: "ZAR", name: "currency_south_african_rand".localized, type: .fiat),
        Currency(code: "RUB", name: "currency_russian_ruble".localized, type: .fiat),
        
        // TIER 3: Rest alphabetically (regional/emerging markets)
        Currency(code: "AED", name: "currency_uae_dirham".localized, type: .fiat),
        Currency(code: "AFN", name: "currency_afghan_afghani".localized, type: .fiat),
        Currency(code: "ALL", name: "currency_albanian_lek".localized, type: .fiat),
        Currency(code: "AMD", name: "currency_armenian_dram".localized, type: .fiat),
        Currency(code: "ANG", name: "currency_netherlands_antillean_guilder".localized, type: .fiat),
        Currency(code: "AOA", name: "currency_angolan_kwanza".localized, type: .fiat),
        Currency(code: "ARS", name: "currency_argentine_peso".localized, type: .fiat),
        Currency(code: "AWG", name: "currency_aruban_florin".localized, type: .fiat),
        Currency(code: "AZN", name: "currency_azerbaijani_manat".localized, type: .fiat),
        Currency(code: "BAM", name: "currency_bosnia_herzegovina_convertible_mark".localized, type: .fiat),
        Currency(code: "BBD", name: "currency_barbadian_dollar".localized, type: .fiat),
        Currency(code: "BDT", name: "currency_bangladeshi_taka".localized, type: .fiat),
        Currency(code: "BGN", name: "currency_bulgarian_lev".localized, type: .fiat),
        Currency(code: "BHD", name: "currency_bahraini_dinar".localized, type: .fiat),
        Currency(code: "BIF", name: "currency_burundian_franc".localized, type: .fiat),
        Currency(code: "BMD", name: "currency_bermudian_dollar".localized, type: .fiat),
        Currency(code: "BND", name: "currency_brunei_dollar".localized, type: .fiat),
        Currency(code: "BOB", name: "currency_bolivian_boliviano".localized, type: .fiat),
        Currency(code: "BSD", name: "currency_bahamian_dollar".localized, type: .fiat),
        Currency(code: "BTN", name: "currency_bhutanese_ngultrum".localized, type: .fiat),
        Currency(code: "BWP", name: "currency_botswanan_pula".localized, type: .fiat),
        Currency(code: "BYN", name: "currency_belarusian_ruble".localized, type: .fiat),
        Currency(code: "BZD", name: "currency_belize_dollar".localized, type: .fiat),
        Currency(code: "CDF", name: "currency_congolese_franc".localized, type: .fiat),
        Currency(code: "CLP", name: "currency_chilean_peso".localized, type: .fiat),
        Currency(code: "COP", name: "currency_colombian_peso".localized, type: .fiat),
        Currency(code: "CRC", name: "currency_costa_rican_colon".localized, type: .fiat),
        Currency(code: "CUC", name: "currency_cuban_convertible_peso".localized, type: .fiat),
        Currency(code: "CUP", name: "currency_cuban_peso".localized, type: .fiat),
        Currency(code: "CVE", name: "currency_cape_verdean_escudo".localized, type: .fiat),
        Currency(code: "CZK", name: "currency_czech_koruna".localized, type: .fiat),
        Currency(code: "DJF", name: "currency_djiboutian_franc".localized, type: .fiat),
        Currency(code: "DOP", name: "currency_dominican_peso".localized, type: .fiat),
        Currency(code: "DZD", name: "currency_algerian_dinar".localized, type: .fiat),
        Currency(code: "EGP", name: "currency_egyptian_pound".localized, type: .fiat),
        Currency(code: "ERN", name: "currency_eritrean_nakfa".localized, type: .fiat),
        Currency(code: "ETB", name: "currency_ethiopian_birr".localized, type: .fiat),
        Currency(code: "FJD", name: "currency_fijian_dollar".localized, type: .fiat),
        Currency(code: "FKP", name: "currency_falkland_islands_pound".localized, type: .fiat),
        Currency(code: "FOK", name: "currency_faroese_krona".localized, type: .fiat),
        Currency(code: "GEL", name: "currency_georgian_lari".localized, type: .fiat),
        Currency(code: "GGP", name: "currency_guernsey_pound".localized, type: .fiat),
        Currency(code: "GHS", name: "currency_ghanaian_cedi".localized, type: .fiat),
        Currency(code: "GIP", name: "currency_gibraltar_pound".localized, type: .fiat),
        Currency(code: "GMD", name: "currency_gambian_dalasi".localized, type: .fiat),
        Currency(code: "GNF", name: "currency_guinean_franc".localized, type: .fiat),
        Currency(code: "GTQ", name: "currency_guatemalan_quetzal".localized, type: .fiat),
        Currency(code: "GYD", name: "currency_guyanaese_dollar".localized, type: .fiat),
        Currency(code: "HNL", name: "currency_honduran_lempira".localized, type: .fiat),
        Currency(code: "HRK", name: "currency_croatian_kuna".localized, type: .fiat),
        Currency(code: "HTG", name: "currency_haitian_gourde".localized, type: .fiat),
        Currency(code: "HUF", name: "currency_hungarian_forint".localized, type: .fiat),
        Currency(code: "IDR", name: "currency_indonesian_rupiah".localized, type: .fiat),
        Currency(code: "ILS", name: "currency_israeli_shekel".localized, type: .fiat),
        Currency(code: "IMP", name: "currency_manx_pound".localized, type: .fiat),
        Currency(code: "IQD", name: "currency_iraqi_dinar".localized, type: .fiat),
        Currency(code: "IRR", name: "currency_iranian_rial".localized, type: .fiat),
        Currency(code: "ISK", name: "currency_icelandic_krona".localized, type: .fiat),
        Currency(code: "JEP", name: "currency_jersey_pound".localized, type: .fiat),
        Currency(code: "JMD", name: "currency_jamaican_dollar".localized, type: .fiat),
        Currency(code: "JOD", name: "currency_jordanian_dinar".localized, type: .fiat),
        Currency(code: "KES", name: "currency_kenyan_shilling".localized, type: .fiat),
        Currency(code: "KGS", name: "currency_kyrgyzstani_som".localized, type: .fiat),
        Currency(code: "KHR", name: "currency_cambodian_riel".localized, type: .fiat),
        Currency(code: "KID", name: "currency_kiribati_dollar".localized, type: .fiat),
        Currency(code: "KMF", name: "currency_comorian_franc".localized, type: .fiat),
        Currency(code: "KPW", name: "currency_north_korean_won".localized, type: .fiat),
        Currency(code: "KWD", name: "currency_kuwaiti_dinar".localized, type: .fiat),
        Currency(code: "KYD", name: "currency_cayman_islands_dollar".localized, type: .fiat),
        Currency(code: "KZT", name: "currency_kazakhstani_tenge".localized, type: .fiat),
        Currency(code: "LAK", name: "currency_laotian_kip".localized, type: .fiat),
        Currency(code: "LBP", name: "currency_lebanese_pound".localized, type: .fiat),
        Currency(code: "LKR", name: "currency_sri_lankan_rupee".localized, type: .fiat),
        Currency(code: "LRD", name: "currency_liberian_dollar".localized, type: .fiat),
        Currency(code: "LSL", name: "currency_lesotho_loti".localized, type: .fiat),
        Currency(code: "LTL", name: "currency_lithuanian_litas".localized, type: .fiat),
        Currency(code: "LVL", name: "currency_latvian_lats".localized, type: .fiat),
        Currency(code: "LYD", name: "currency_libyan_dinar".localized, type: .fiat),
        Currency(code: "MAD", name: "currency_moroccan_dirham".localized, type: .fiat),
        Currency(code: "MDL", name: "currency_moldovan_leu".localized, type: .fiat),
        Currency(code: "MGA", name: "currency_malagasy_ariary".localized, type: .fiat),
        Currency(code: "MKD", name: "currency_macedonian_denar".localized, type: .fiat),
        Currency(code: "MMK", name: "currency_myanmar_kyat".localized, type: .fiat),
        Currency(code: "MNT", name: "currency_mongolian_tugrik".localized, type: .fiat),
        Currency(code: "MOP", name: "currency_macanese_pataca".localized, type: .fiat),
        Currency(code: "MRU", name: "currency_mauritanian_ouguiya".localized, type: .fiat),
        Currency(code: "MUR", name: "currency_mauritian_rupee".localized, type: .fiat),
        Currency(code: "MVR", name: "currency_maldivian_rufiyaa".localized, type: .fiat),
        Currency(code: "MWK", name: "currency_malawian_kwacha".localized, type: .fiat),
        Currency(code: "MYR", name: "currency_malaysian_ringgit".localized, type: .fiat),
        Currency(code: "MZN", name: "currency_mozambican_metical".localized, type: .fiat),
        Currency(code: "NAD", name: "currency_namibian_dollar".localized, type: .fiat),
        Currency(code: "NGN", name: "currency_nigerian_naira".localized, type: .fiat),
        Currency(code: "NIO", name: "currency_nicaraguan_cordoba".localized, type: .fiat),
        Currency(code: "NPR", name: "currency_nepalese_rupee".localized, type: .fiat),
        Currency(code: "OMR", name: "currency_omani_rial".localized, type: .fiat),
        Currency(code: "PAB", name: "currency_panamanian_balboa".localized, type: .fiat),
        Currency(code: "PEN", name: "currency_peruvian_sol".localized, type: .fiat),
        Currency(code: "PGK", name: "currency_papua_new_guinean_kina".localized, type: .fiat),
        Currency(code: "PHP", name: "currency_philippine_peso".localized, type: .fiat),
        Currency(code: "PKR", name: "currency_pakistani_rupee".localized, type: .fiat),
        Currency(code: "PLN", name: "currency_polish_zloty".localized, type: .fiat),
        Currency(code: "PYG", name: "currency_paraguayan_guarani".localized, type: .fiat),
        Currency(code: "QAR", name: "currency_qatari_riyal".localized, type: .fiat),
        Currency(code: "RON", name: "currency_romanian_leu".localized, type: .fiat),
        Currency(code: "RSD", name: "currency_serbian_dinar".localized, type: .fiat),
        Currency(code: "RWF", name: "currency_rwandan_franc".localized, type: .fiat),
        Currency(code: "SAR", name: "currency_saudi_riyal".localized, type: .fiat),
        Currency(code: "SBD", name: "currency_solomon_islands_dollar".localized, type: .fiat),
        Currency(code: "SCR", name: "currency_seychellois_rupee".localized, type: .fiat),
        Currency(code: "SDG", name: "currency_sudanese_pound".localized, type: .fiat),
        Currency(code: "SHP", name: "currency_saint_helena_pound".localized, type: .fiat),
        Currency(code: "SLL", name: "currency_sierra_leonean_leone".localized, type: .fiat),
        Currency(code: "SOS", name: "currency_somali_shilling".localized, type: .fiat),
        Currency(code: "SRD", name: "currency_surinamese_dollar".localized, type: .fiat),
        Currency(code: "SSP", name: "currency_south_sudanese_pound".localized, type: .fiat),
        Currency(code: "STD", name: "currency_sao_tome_and_principe_dobra".localized, type: .fiat),
        Currency(code: "SVC", name: "currency_salvadoran_colon".localized, type: .fiat),
        Currency(code: "SYP", name: "currency_syrian_pound".localized, type: .fiat),
        Currency(code: "SZL", name: "currency_swazi_lilangeni".localized, type: .fiat),
        Currency(code: "THB", name: "currency_thai_baht".localized, type: .fiat),
        Currency(code: "TJS", name: "currency_tajikistani_somoni".localized, type: .fiat),
        Currency(code: "TMT", name: "currency_turkmenistan_manat".localized, type: .fiat),
        Currency(code: "TND", name: "currency_tunisian_dinar".localized, type: .fiat),
        Currency(code: "TOP", name: "currency_tongan_paanga".localized, type: .fiat),
        Currency(code: "TRY", name: "currency_turkish_lira".localized, type: .fiat),
        Currency(code: "TTD", name: "currency_trinidad_and_tobago_dollar".localized, type: .fiat),
        Currency(code: "TVD", name: "currency_tuvaluan_dollar".localized, type: .fiat),
        Currency(code: "TWD", name: "currency_taiwan_new_dollar".localized, type: .fiat),
        Currency(code: "TZS", name: "currency_tanzanian_shilling".localized, type: .fiat),
        Currency(code: "UAH", name: "currency_ukrainian_hryvnia".localized, type: .fiat),
        Currency(code: "UGX", name: "currency_ugandan_shilling".localized, type: .fiat),
        Currency(code: "UYU", name: "currency_uruguayan_peso".localized, type: .fiat),
        Currency(code: "UZS", name: "currency_uzbekistani_som".localized, type: .fiat),
        Currency(code: "VES", name: "currency_venezuelan_bolivar".localized, type: .fiat),
        Currency(code: "VND", name: "currency_vietnamese_dong".localized, type: .fiat),
        Currency(code: "VUV", name: "currency_vanuatu_vatu".localized, type: .fiat),
        Currency(code: "WST", name: "currency_samoan_tala".localized, type: .fiat),
        Currency(code: "XAF", name: "currency_central_african_cfa_franc".localized, type: .fiat),
        Currency(code: "XCD", name: "currency_east_caribbean_dollar".localized, type: .fiat),
        Currency(code: "XOF", name: "currency_west_african_cfa_franc".localized, type: .fiat),
        Currency(code: "XPF", name: "currency_cfp_franc".localized, type: .fiat),
        Currency(code: "YER", name: "currency_yemeni_rial".localized, type: .fiat),
        Currency(code: "ZAR", name: "currency_south_african_rand".localized, type: .fiat),
        Currency(code: "ZMK", name: "currency_zambian_kwacha_old".localized, type: .fiat),
        Currency(code: "ZMW", name: "currency_zambian_kwacha".localized, type: .fiat),
        Currency(code: "ZWL", name: "currency_zimbabwean_dollar".localized, type: .fiat)
    ]
    
    static let cryptoCurrencies: [Currency] = [
        // TOP 10: By market cap ranking (January 2025)
        Currency(code: "BTC", name: "Bitcoin", type: .crypto),
        Currency(code: "ETH", name: "Ethereum", type: .crypto),
        Currency(code: "USDT", name: "Tether", type: .crypto),
        Currency(code: "XRP", name: "XRP", type: .crypto),
        Currency(code: "BNB", name: "BNB", type: .crypto),
        Currency(code: "SOL", name: "Solana", type: .crypto),
        Currency(code: "USDC", name: "USD Coin", type: .crypto),
        Currency(code: "DOGE", name: "Dogecoin", type: .crypto),
        Currency(code: "ADA", name: "Cardano", type: .crypto),
        Currency(code: "TRX", name: "TRON", type: .crypto),
        
        // TIER 2: Major altcoins (Top 11-25)
        Currency(code: "AVAX", name: "Avalanche", type: .crypto),
        Currency(code: "TON", name: "Toncoin", type: .crypto),
        Currency(code: "LINK", name: "Chainlink", type: .crypto),
        Currency(code: "DOT", name: "Polkadot", type: .crypto),
        Currency(code: "WBTC", name: "Wrapped Bitcoin", type: .crypto),
        Currency(code: "LTC", name: "Litecoin", type: .crypto),
        Currency(code: "UNI", name: "Uniswap", type: .crypto),
        Currency(code: "ATOM", name: "Cosmos", type: .crypto),
        Currency(code: "ICP", name: "Internet Computer", type: .crypto),
        Currency(code: "STETH", name: "Lido Staked Ether", type: .crypto),
        
        // TIER 3: Rest by popularity/volume (alphabetical)
        Currency(code: "AAVE", name: "Aave", type: .crypto),
        Currency(code: "ALGO", name: "Algorand", type: .crypto),
        Currency(code: "APT", name: "Aptos", type: .crypto),
        Currency(code: "ARB", name: "Arbitrum", type: .crypto),
        Currency(code: "AXS", name: "Axie Infinity", type: .crypto),
        Currency(code: "BCH", name: "Bitcoin Cash", type: .crypto),
        Currency(code: "BGB", name: "Bitget Token", type: .crypto),
        Currency(code: "BUSD", name: "Binance USD", type: .crypto),
        Currency(code: "CFX", name: "Conflux", type: .crypto),
        Currency(code: "CRO", name: "Cronos", type: .crypto),
        Currency(code: "DAI", name: "Dai", type: .crypto),
        Currency(code: "EGLD", name: "MultiversX", type: .crypto),
        Currency(code: "ETC", name: "Ethereum Classic", type: .crypto),
        Currency(code: "FIL", name: "Filecoin", type: .crypto),
        Currency(code: "FLR", name: "Flare", type: .crypto),
        Currency(code: "GRT", name: "The Graph", type: .crypto),
        Currency(code: "HBAR", name: "Hedera", type: .crypto),
        Currency(code: "INJ", name: "Injective", type: .crypto),
        Currency(code: "JLP", name: "Jupiter", type: .crypto),
        Currency(code: "KAS", name: "Kaspa", type: .crypto),
        Currency(code: "LDO", name: "Lido DAO", type: .crypto),
        Currency(code: "LEO", name: "UNUS SED LEO", type: .crypto),
        Currency(code: "LUNC", name: "Terra Luna Classic", type: .crypto),
        Currency(code: "METH", name: "Mantle Staked Ether", type: .crypto),
        Currency(code: "NEAR", name: "NEAR Protocol", type: .crypto),
        Currency(code: "OP", name: "Optimism", type: .crypto),
        Currency(code: "POL", name: "Polygon", type: .crypto),
        Currency(code: "PYTH", name: "Pyth Network", type: .crypto),
        Currency(code: "QNT", name: "Quant", type: .crypto),
        Currency(code: "RENDER", name: "Render", type: .crypto),
        Currency(code: "SEI", name: "Sei", type: .crypto),
        Currency(code: "SHIB", name: "Shiba Inu", type: .crypto),
        Currency(code: "STX", name: "Stacks", type: .crypto),
        Currency(code: "SUI", name: "Sui", type: .crypto),
        Currency(code: "TAO", name: "Bittensor", type: .crypto),
        Currency(code: "THETA", name: "Theta Network", type: .crypto),
        Currency(code: "TIA", name: "Celestia", type: .crypto),
        Currency(code: "VET", name: "VeChain", type: .crypto),
        Currency(code: "WBT", name: "WhiteBIT Token", type: .crypto),
        Currency(code: "XLM", name: "Stellar", type: .crypto),
        Currency(code: "XMR", name: "Monero", type: .crypto),
        Currency(code: "XTZ", name: "Tezos", type: .crypto),
        Currency(code: "ZEC", name: "Zcash", type: .crypto)
    ]
    
    static func getCurrencies(for type: Currency.CurrencyType) -> [Currency] {
        switch type {
        case .fiat:
            return fiatCurrencies // Already sorted: top currencies first, then alphabetical
        case .crypto:
            return cryptoCurrencies // Already sorted: by market cap ranking
        }
    }
    
    static func findCurrency(by code: String) -> Currency? {
        let allCurrencies = fiatCurrencies + cryptoCurrencies
        return allCurrencies.first { $0.code == code }
    }
    
    static func searchCurrencies(query: String, type: Currency.CurrencyType? = nil) -> [Currency] {
        let currencies = type == nil ? (fiatCurrencies + cryptoCurrencies) : getCurrencies(for: type!)
        
        if query.isEmpty {
            return currencies
        }
        
        return currencies.filter { currency in
            currency.code.lowercased().contains(query.lowercased()) ||
            currency.name.lowercased().contains(query.lowercased())
        }
    }
}
